name: Inputs
author: fingerflow
current: 1.0.0
tags: [Form, Input]
copyright: "&copy; [Arian Stolwijk](http://www.aryweb.nl) and [MonkeyPhysics.com](http://monkeyphysics.com)"
license: MIT
description: MooTools Input manager class

sources:
  - Source/Input.js
  - Source/Input.Dependencies.js
  - Source/Input.Handlers.js
  - Source/Input.Default.js
  - Source/Input.Check.js
  - Source/Input.Text.js
  - Source/Input.HTML.js
  - Source/Input.Date.js
  - Source/Input.Date.Time.js
  - Source/Input.File.js
  - Source/Input.Multiple.Text.js
  