name: Input
author: fingerflow
current: 1.0.0
tags: [Form, Input]
copyright: "&copy; [Arian Stolwijk](http://www.aryweb.nl) and [MonkeyPhysics.com](http://monkeyphysics.com)"
license: MIT
description: MooTools Input manager class

sources:
  - Sources/Anchor.js
  - Sources/Anchor-after.js
  - Sources/Input.js
  - Sources/Input.Dependencies.js
  - Sources/Input.Handlers.js
  - Sources/Input.Default.js
  - Sources/Input.Check.js
  - Sources/Input.Text.js
  - Sources/Input.HTML.js
  - Sources/Input.Date.js
  - Sources/Input.Date.Time.js
  - Sources/Input.File.js
  - Sources/Input.Multiple.Text.js
  